### Promise
javascriptにおいて非同期処理のすおさが完了したときに結果を返すもの　　
promiseは`resolve`と`reject`、二つの関数を引数に取る  
`resolve`:処理が成功したときのメッセージを表示する関数  
`reject`:処理が失敗したときのメッセージを表示する関数  
```javascript
new Promise(function(resolve, reject){
    resolve('成功');
});

new Promise(function(resolve, reject){
    reject('失敗');
});
```

後述する`then`と`catch`はpromiseの状態によってどちらが呼び出されるか決まる　　
成功(`fulfilled`・`resolve`)の時は`then`が呼び出される　　
失敗(`rejected`)の時は`catch`が呼び出される  

### then
Promiseオブジェクトに使用される非同期処理を扱うためのメソッド 　
`then`メソッドを使うことで、非同期処理成功後に実行したい処理を定義できる　　
`catch`メソッドを使うことで、非同期処理失敗時に実行したい処理を定義できる　　
　　  
チェーンで処理をつなげることもできる
```javascript
const promise = fetch('https://weather.tsukumijima.net/api/forecast/city/250010');

promise
  .then(response => {
    console.log(response);
  })
  .catch(error => {
    console.log(error);
  });
```
上記のように記述してもpromiseの状態によってどちらが呼び出されるかは異なるため競合は起こらない。そのため処理をわけることができる。


### fetchAPI